//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int User_ID { get; set; }
        public Nullable<int> Segment_ID { get; set; }
        public decimal Balance1 { get; set; }
        public decimal Frozen_Balance { get; set; }
        public System.DateTime Insert_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    
        public virtual Segment Segment { get; set; }
        public virtual User User { get; set; }
    }
}
