//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrozenBalance
    {
        public int FozenBalance_ID { get; set; }
        public int User_ID { get; set; }
        public int Symbol_ID { get; set; }
        public decimal Balance { get; set; }
        public bool IsReleased { get; set; }
        public string Comments { get; set; }
        public System.DateTime Insert_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    
        public virtual Symbol Symbol { get; set; }
        public virtual User User { get; set; }
    }
}
