//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorySymbol
    {
        public int History_Symbol_ID { get; set; }
        public int Symbol_ID { get; set; }
        public string History_Symbol { get; set; }
        public int History_Source_ID { get; set; }
        public int DevidedBy { get; set; }
        public int MultipliedBy { get; set; }
    
        public virtual History_Source History_Source { get; set; }
        public virtual Symbol Symbol { get; set; }
    }
}
