//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status_History
    {
        public int Order_Status_History_ID { get; set; }
        public int Order_ID { get; set; }
        public int Order_Status_ID { get; set; }
        public string Status_Updated_By { get; set; }
        public System.DateTime Insert_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    
        public virtual Order_Status Order_Status { get; set; }
        public virtual OrderBook OrderBook { get; set; }
    }
}
