//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformPermission
    {
        public int Platform_Permission_ID { get; set; }
        public int Platform_ID { get; set; }
        public int User_ID { get; set; }
    
        public virtual Platform Platform { get; set; }
        public virtual User User { get; set; }
    }
}
