//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Symbol()
        {
            this.DOMSymbols = new HashSet<DOMSymbol>();
            this.FeedSymbols = new HashSet<FeedSymbol>();
            this.FrozenBalances = new HashSet<FrozenBalance>();
            this.History_OrderBook = new HashSet<History_OrderBook>();
            this.HistorySymbols = new HashSet<HistorySymbol>();
            this.OrderBooks = new HashSet<OrderBook>();
        }
    
        public int Symbol_ID { get; set; }
        public int Base_Symbol_ID { get; set; }
        public string Symbol1 { get; set; }
        public string Additional_Description { get; set; }
        public int MinVolPerOrder { get; set; }
        public int MaxVolPerOrder { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool Enabled { get; set; }
        public int TotalPositionLimit { get; set; }
        public Nullable<System.DateTime> ContractExpiryDate { get; set; }
        public bool HasDOM { get; set; }
        public bool MaintainHistory { get; set; }
        public int ExecutionType { get; set; }
    
        public virtual Base_Symbol Base_Symbol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOMSymbol> DOMSymbols { get; set; }
        public virtual ExecutionType ExecutionType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedSymbol> FeedSymbols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrozenBalance> FrozenBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_OrderBook> History_OrderBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorySymbol> HistorySymbols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBook> OrderBooks { get; set; }
    }
}
