//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_ID { get; set; }
        public int User_ID { get; set; }
        public int Transaction_Type_ID { get; set; }
        public Nullable<int> B_Order_ID { get; set; }
        public Nullable<decimal> B_Order_Commission { get; set; }
        public Nullable<int> S_Order_ID { get; set; }
        public Nullable<decimal> S_Order_Commission { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Insert_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
        public string Comments { get; set; }
    
        public virtual OrderBook OrderBook { get; set; }
        public virtual OrderBook OrderBook1 { get; set; }
        public virtual Transaction_Types Transaction_Types { get; set; }
        public virtual User User { get; set; }
    }
}
