//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.FrozenBalances = new HashSet<FrozenBalance>();
            this.History_OrderBook = new HashSet<History_OrderBook>();
            this.History_Transactions = new HashSet<History_Transactions>();
            this.ModulePermissions = new HashSet<ModulePermission>();
            this.OrderBooks = new HashSet<OrderBook>();
            this.PlatformPermissions = new HashSet<PlatformPermission>();
            this.Segment_Permissions = new HashSet<Segment_Permissions>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int User_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime Registration_Date { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int City_ID { get; set; }
        public int Currency_ID { get; set; }
        public int Balance_Type { get; set; }
        public Nullable<int> Office_ID { get; set; }
        public byte Enabled { get; set; }
        public byte EnableLiquidation { get; set; }
        public Nullable<int> Liquidation_Type_ID { get; set; }
        public Nullable<decimal> LiquidateLevel { get; set; }
        public int ExecutionType { get; set; }
        public byte MarginOnLimits { get; set; }
        public byte UseCurrentPLForMargin { get; set; }
    
        public virtual Balance Balance { get; set; }
        public virtual Balance_Types Balance_Types { get; set; }
        public virtual City City { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ExecutionType ExecutionType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrozenBalance> FrozenBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_OrderBook> History_OrderBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_Transactions> History_Transactions { get; set; }
        public virtual Liquidation_Types Liquidation_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePermission> ModulePermissions { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBook> OrderBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatformPermission> PlatformPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Segment_Permissions> Segment_Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
